default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: text_todo_development

test:
  <<: *default
  database: text_todo_test

production:
  <<: *default
  database: text_todo_production
  username: text_todo
  password: <%= ENV['TEXT_TODO_DATABASE_PASSWORD'] %>