defaults: &default
  todoist_auth_token: <%= ENV['TODOIST_AUTH_TOKEN'] %>
  todoist_list_name: <%= ENV['TODOIST_LIST_NAME'] %>

development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default