defaults: &default
  todoist_auth_token: <%= ENV['TODOIST_AUTH_TOKEN'] %>
  todoist_list_name: <%= ENV['TODOIST_LIST_NAME'] %>
  twilio_account_sid: <%= ENV['TWILIO_ACCOUNT_SID'] %>
  twilio_auth_token: <%= ENV['TWILIO_AUTH_TOKEN'] %>

development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default