defaults: &default
  todoist_auth_token: <%= ENV['TODOIST_AUTH_TOKEN'] %>
  todoist_list_name: <%= ENV['TODOIST_LIST_NAME'] %>
  twilio_auth_token: <%= ENV['TWILIO_AUTH_TOKEN'] %>
  twilio_phone_number: <%= ENV['TWILIO_PHONE_NUMBER'] %>

development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default